<a href="https://colab.research.google.com/github/Sachinsachin21/Python-library/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
S = list(range(1,11))  #create list
S

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
P = np.array(S) #transform list into numpy array
P

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
type(P)   #check datatype

numpy.ndarray

In [ ]:
for i in P: #same as lists, ndarrays store multiple elements
    print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
S = [1,2.5,"Dog",True] #list can store different datatype

In [ ]:
for i in S:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [ ]:
A = np.array(S)   #in ndarrays, all elements must have same datatype: numpy transforms atomatically
A

array(['1', '2.5', 'Dog', 'True'], dtype='<U32')

In [ ]:
for i in A:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
B = np.array([1.,.2,"3",.4,5])
B

array(['1.0', '0.2', '3', '0.4', '5'], dtype='<U32')

In [ ]:
type(B)

numpy.ndarray

In [ ]:
B.dtype  # cna check single dtype

dtype('<U32')

In [ ]:
np.arange(0,21,5) #create new ndarray

array([ 0,  5, 10, 15, 20])

In [ ]:
W = [1,2,3]
W

[1, 2, 3]

In [ ]:
W*3 # not a element wise operator

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
W1=[] # elemnt-wise pot with lists require a bunch of code
for i in W:
    W1.append(i**3)
W1

[1, 8, 27]

In [ ]:
W2 = np.arange(1,21)
W3 = W2.reshape(4,5)
W3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
W2**2 #all elements squared

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [ ]:
W2+4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [ ]:
2**W2 #can serve as exponent as well

array([      2,       4,       8,      16,      32,      64,     128,
           256,     512,    1024,    2048,    4096,    8192,   16384,
         32768,   65536,  131072,  262144,  524288, 1048576])

In [ ]:
np.sqrt(W2) #square root of all elements

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [ ]:
np.exp(W2)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [ ]:
np.set_printoptions(precision=2,suppress=True) #set precision and suppress

In [ ]:
np.log(W2)

array([0.  , 0.69, 1.1 , 1.39, 1.61, 1.79, 1.95, 2.08, 2.2 , 2.3 , 2.4 ,
       2.48, 2.56, 2.64, 2.71, 2.77, 2.83, 2.89, 2.94, 3.  ])

In [ ]:
W2.sum()

210

In [ ]:
np.sum(W2)  #same as above

210

In [ ]:
W2.size #number of elements

20

In [ ]:
len(W2) #number of rows

20

In [ ]:
E = np.array([-1,-2,0.5,1,3,4.5])
E

array([-1. , -2. ,  0.5,  1. ,  3. ,  4.5])

In [ ]:
np.abs(E) #absolute value

array([1. , 2. , 0.5, 1. , 3. , 4.5])

In [ ]:
R = np.array([-1.2,-2.8,0.6,1.4,2.9,3.7])
R

array([-1.2, -2.8,  0.6,  1.4,  2.9,  3.7])

In [ ]:
np.ceil(R) #round up

array([-1., -2.,  1.,  2.,  3.,  4.])

In [ ]:
np.floor(R) #round down

array([-2., -3.,  0.,  1.,  2.,  3.])

In [ ]:
np.around([-3.23,-0.76,1.45,2.78],decimals=3) #round to a certain number of decimal places

array([-3.23, -0.76,  1.45,  2.78])

In [ ]:
W2[0] #first element

1

In [ ]:
W2[2] #third element

3

In [ ]:
W2[-1] #last element

20

In [ ]:
list(enumerate(W2)) #enumerate elements list of index, value tuples

[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (6, 7),
 (7, 8),
 (8, 9),
 (9, 10),
 (10, 11),
 (11, 12),
 (12, 13),
 (13, 14),
 (14, 15),
 (15, 16),
 (16, 17),
 (17, 18),
 (18, 19),
 (19, 20)]

In [ ]:
W2[2:6] #slice

array([3, 4, 5, 6])

In [ ]:
W2[2:16:2] #slice with step

array([ 3,  5,  7,  9, 11, 13, 15])

In [ ]:
W2[::3] #slice with step

array([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
W2[7::-1] #reverse

array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
W2[7]=33
W2

array([ 1,  2,  3,  4,  5,  6,  7, 33,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
W2[-1]=21
W2

array([ 1,  2,  3,  4,  5,  6,  7, 33,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21])

In [ ]:
W2[12:17]=[23,31,44,56,77]
W2

array([ 1,  2,  3,  4,  5,  6,  7, 33,  9, 10, 11, 12, 23, 31, 44, 56, 77,
       18, 19, 21])

In [ ]:
W2[2:4]=[42,43]
W2

array([ 1,  2, 42, 43,  5,  6,  7, 33,  9, 10, 11, 12, 23, 31, 44, 56, 77,
       18, 19, 21])

In [ ]:
Q = W2[2:8]
Q

array([42, 43,  5,  6,  7, 33])

In [ ]:
Q[0]=10
Q

array([10, 43,  5,  6,  7, 33])

In [ ]:
D = Q[3:6]
D

array([ 6,  7, 33])

In [ ]:
W2.shape

(20,)

In [ ]:
W2=W2.reshape(4,5) #reshape
W2

array([[ 1,  2, 10, 43,  5],
       [ 6,  7, 33,  9, 10],
       [11, 12, 23, 31, 44],
       [56, 77, 18, 19, 21]])

In [ ]:
W2.shape

(4, 5)

In [ ]:
W2 + 21

array([[22, 23, 31, 64, 26],
       [27, 28, 54, 30, 31],
       [32, 33, 44, 52, 65],
       [77, 98, 39, 40, 42]])

In [ ]:
W3 = W2.reshape(5,2,2)
W3

array([[[ 1,  2],
        [10, 43]],

       [[ 5,  6],
        [ 7, 33]],

       [[ 9, 10],
        [11, 12]],

       [[23, 31],
        [44, 56]],

       [[77, 18],
        [19, 21]]])

In [ ]:
W4 = np.arange(1,101).reshape(10,10) # 2-dim ndarray
W4

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
W2[3][3] #third row, third column

19

In [ ]:
W2[3,3] #same as above

19

In [ ]:
W2[-3,-3] #last row, last column

33

In [ ]:
W2[1:4,1:4]

array([[ 7, 33,  9],
       [12, 23, 31],
       [77, 18, 19]])

In [ ]:
W2.T #transpose

array([[ 1,  6, 11, 56],
       [ 2,  7, 12, 77],
       [10, 33, 23, 18],
       [43,  9, 31, 19],
       [ 5, 10, 44, 21]])

In [ ]:
W2.transpose() #same as above

array([[ 1,  6, 11, 56],
       [ 2,  7, 12, 77],
       [10, 33, 23, 18],
       [43,  9, 31, 19],
       [ 5, 10, 44, 21]])

In [ ]:
W2.flatten() #flatten

array([ 1,  2, 10, 43,  5,  6,  7, 33,  9, 10, 11, 12, 23, 31, 44, 56, 77,
       18, 19, 21])

In [ ]:
W2[2:,-1] = W2[2:,-1]/4  #change last column
W2

array([[ 1,  2, 10, 43,  5],
       [ 6,  7, 33,  9, 10],
       [11, 12, 23, 31, 11],
       [56, 77, 18, 19,  5]])

In [ ]:
W4.cumsum() #cumulative sum

array([   1,    3,    6,   10,   15,   21,   28,   36,   45,   55,   66,
         78,   91,  105,  120,  136,  153,  171,  190,  210,  231,  253,
        276,  300,  325,  351,  378,  406,  435,  465,  496,  528,  561,
        595,  630,  666,  703,  741,  780,  820,  861,  903,  946,  990,
       1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485, 1540,
       1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145, 2211,
       2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926, 3003,
       3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828, 3916,
       4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851, 4950,
       5050])

In [ ]:
W4.sum(axis=0) #sum all elements

array([460, 470, 480, 490, 500, 510, 520, 530, 540, 550])

In [ ]:
W4.sum(axis=1)

array([ 55, 155, 255, 355, 455, 555, 655, 755, 855, 955])

In [ ]:
W4.cumsum(axis=0)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 12,  14,  16,  18,  20,  22,  24,  26,  28,  30],
       [ 33,  36,  39,  42,  45,  48,  51,  54,  57,  60],
       [ 64,  68,  72,  76,  80,  84,  88,  92,  96, 100],
       [105, 110, 115, 120, 125, 130, 135, 140, 145, 150],
       [156, 162, 168, 174, 180, 186, 192, 198, 204, 210],
       [217, 224, 231, 238, 245, 252, 259, 266, 273, 280],
       [288, 296, 304, 312, 320, 328, 336, 344, 352, 360],
       [369, 378, 387, 396, 405, 414, 423, 432, 441, 450],
       [460, 470, 480, 490, 500, 510, 520, 530, 540, 550]])

In [ ]:
W4.cumsum(axis=1)

array([[  1,   3,   6,  10,  15,  21,  28,  36,  45,  55],
       [ 11,  23,  36,  50,  65,  81,  98, 116, 135, 155],
       [ 21,  43,  66,  90, 115, 141, 168, 196, 225, 255],
       [ 31,  63,  96, 130, 165, 201, 238, 276, 315, 355],
       [ 41,  83, 126, 170, 215, 261, 308, 356, 405, 455],
       [ 51, 103, 156, 210, 265, 321, 378, 436, 495, 555],
       [ 61, 123, 186, 250, 315, 381, 448, 516, 585, 655],
       [ 71, 143, 216, 290, 365, 441, 518, 596, 675, 755],
       [ 81, 163, 246, 330, 415, 501, 588, 676, 765, 855],
       [ 91, 183, 276, 370, 465, 561, 658, 756, 855, 955]])

In [ ]:
W2.prod() #product

-636374101439818752

In [ ]:
W2.prod(axis=0) #product of each column

array([  3696,  12936, 136620, 227943,   2750])

In [ ]:
W2.prod(axis=1) #product of each row

array([   4300,  124740, 1035276, 7373520])

In [ ]:
Y = np.arange(1,11)
Y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
M1 = Y >5
M1

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
M2 = Y%2==0
M2

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
M3 = Y<8
M3

array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False])

In [ ]:
M4 = (Y>5) & (Y<8) #bitwise and
M4

array([False, False, False, False, False,  True,  True, False, False,
       False])

In [ ]:
#M4 = (Y>5) | (Y<8) #bitwise or
#M4

In [ ]:
M5 = ~((Y>5) & (Y<8)) #bitwise not
M5

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True])

In [ ]:
Y[Y>5] #elements greater than 5

array([ 6,  7,  8,  9, 10])

In [ ]:
Y[M1] #same as above

array([ 6,  7,  8,  9, 10])

In [ ]:
Y[M2] #even numbers

array([ 2,  4,  6,  8, 10])

In [ ]:
Y[M3] #less than 8

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
Y[M4] #between 5 and 8

array([6, 7])

In [ ]:
np.random.seed(123) #set seed
np.random.randint(1,101,10) #random integer

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48])

In [ ]:
np.random.rand(2,5) #random float

array([[0.39, 0.34, 0.73, 0.44, 0.06],
       [0.4 , 0.74, 0.18, 0.18, 0.53]])

In [ ]:
np.random.normal(2,1,3) #random normal

array([4.21, 2.52, 2.47])

In [ ]:
W5 = np.arange(1,101)

In [ ]:
np.random.shuffle(W5) #shuffle
W5

array([  8,  90,  48,   3,   5,  33,  88,  62,  37,   1,  32,  38,  29,
        58,  46,  30,  25,   9,   6,  17,  14,  81,  60,  47,  21,  92,
        85,  36,  61,  34,  89,  69,  63,  39,  20,  74,  24,  10,  75,
        79,  43,  73,  83,  87,  68,  40,  67,  22,  12,  66,  91,  84,
        64,  80,  49,  42,  54,  45,  52, 100,  18,  82,  13,  50,  57,
        51,  26,  56,  97,  44,   2,  72,  55,  15,   7,  27,  71,  99,
        31,  96,  16,  19,  78,  23,  11,  59,  94,  76,  65,  70,   4,
        41,  77,  35,  28,  95,  86,  98,  53,  93])

In [ ]:
W5.sort() #sort
W5

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
np.random.seed(123)
W6 = np.random.choice(W5,100,replace=False) #random choice
W6

array([  9,  71,  83,  29,  64,   1,   6,  51,  82,   5,  24,  66,  77,
        61,  25,  43,  78,  39,  57,  76,  36,  89,  20,  30,  32,  92,
        86,  10,  54,  42,  22,  91,  34,  70,  85,  88,  96,  98,  63,
        13,  21,  90,  38,  60,   2,  75,  12,  80,  15,  55,  17,  27,
        52,  46,   7,  99,  31,  45,  73,  44,  16,  95,  19,  14,  23,
        11,  59,  72,  65,   4,  41,  35,  28,  53,   8,  49,  62,  94,
       100,  40,   3,  68,  56,  50,  69,  81,  37,  79,  97,  26,  47,
        33,  74,  48,  87,  58,  84,  18,  93,  67])

In [ ]:
np.random.seed(123)
W7 = np.random.choice(W5,100,replace=True) #random choice
W7

array([ 67,  93,  99,  18,  84,  58,  87,  98,  97,  48,  74,  33,  47,
        97,  26,  84,  79,  37,  97,  81,  69,  50,  56,  68,   3,  85,
        40,  67,  85,  48,  62,  49,   8, 100,  93,  53,  98,  86,  95,
        28,  35,  98,  77,  41,   4,  70,  65,  76,  35,  59,  11,  23,
        78,  19,  16,  28,  31,  53,  71,  27,  81,   7,  15,  76,  55,
        72,   2,  44,  59,  56,  26,  51,  85,  57,  50,  13,  19,  82,
         2,  52,  45,  49,  57,  92,  50,  87,   4,  68,  12,  22,  90,
        99,   4,  12,   4,  95,   7,  10,  88,  15])

In [ ]:
np.unique(W7) #unique elements

array([  2,   3,   4,   7,   8,  10,  11,  12,  13,  15,  16,  18,  19,
        22,  23,  26,  27,  28,  31,  33,  35,  37,  40,  41,  44,  45,
        47,  48,  49,  50,  51,  52,  53,  55,  56,  57,  58,  59,  62,
        65,  67,  68,  69,  70,  71,  72,  74,  76,  77,  78,  79,  81,
        82,  84,  85,  86,  87,  88,  90,  92,  93,  95,  97,  98,  99,
       100])

In [ ]:
np.array(list(set(W7)))

array([  2,   3,   4,   7,   8,  10,  11,  12,  13,  15,  16,  18,  19,
        22,  23,  26,  27,  28,  31,  33,  35,  37,  40,  41,  44,  45,
        47,  48,  49,  50,  51,  52,  53,  55,  56,  57,  58,  59,  62,
        65,  67,  68,  69,  70,  71,  72,  74,  76,  77,  78,  79,  81,
        82,  84,  85,  86,  87,  88,  90,  92,  93,  95,  97,  98,  99,
       100])

In [ ]:
np.unique(W7).size

66

In [ ]:
np.unique(W7).shape

(66,)

In [ ]:
np.unique(W7,return_index=True,return_counts=True) #count unique elements

(array([  2,   3,   4,   7,   8,  10,  11,  12,  13,  15,  16,  18,  19,
         22,  23,  26,  27,  28,  31,  33,  35,  37,  40,  41,  44,  45,
         47,  48,  49,  50,  51,  52,  53,  55,  56,  57,  58,  59,  62,
         65,  67,  68,  69,  70,  71,  72,  74,  76,  77,  78,  79,  81,
         82,  84,  85,  86,  87,  88,  90,  92,  93,  95,  97,  98,  99,
        100]),
 array([66, 24, 44, 61, 32, 97, 50, 88, 75, 62, 54,  3, 53, 89, 51, 14, 59,
        39, 56, 11, 40, 17, 26, 43, 67, 80, 12,  9, 31, 21, 71, 79, 35, 64,
        22, 73,  5, 49, 30, 46,  0, 23, 20, 45, 58, 65, 10, 47, 42, 52, 16,
        19, 77,  4, 25, 37,  6, 98, 90, 83,  1, 38,  8,  7,  2, 33]),
 array([2, 1, 4, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1,
        1, 1, 1, 1, 1, 2, 2, 3, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1,
        1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 3, 1, 2, 1, 1, 1, 2, 2, 3, 3, 2, 1]))

In [ ]:
np.unique(W6,return_index=True,return_counts=True) #count unique elements

(array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100]),
 array([ 5, 44, 80, 69,  9,  6, 54, 74,  0, 27, 65, 46, 39, 63, 48, 60, 50,
        97, 62, 22, 40, 30, 64, 10, 14, 89, 51, 72,  3, 23, 56, 24, 91, 32,
        71, 20, 86, 42, 17, 79, 70, 29, 15, 59, 57, 53, 90, 93, 75, 83,  7,
        52, 73, 28, 49, 82, 18, 95, 66, 43, 13, 76, 38,  4, 68, 11, 99, 81,
        84, 33,  1, 67, 58, 92, 45, 19, 12, 16, 87, 47, 85,  8,  2, 96, 34,
        26, 94, 35, 21, 41, 31, 25, 98, 77, 61, 36, 88

In [ ]:
size =7
k = np.arange(size)
len(k)

7

In [ ]:
k1 = np.random.choice(k,size,replace=True)
k1

array([6, 3, 1, 6, 4, 6, 3])

In [ ]:
k2= list(range(size))
len(k2)

7

In [ ]:
%time k+2 #list addition

CPU times: user 35 µs, sys: 5 µs, total: 40 µs
Wall time: 43.4 µs


array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
%timeit k+2

7.17 µs ± 1.36 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit [i+2 for i in k] #list comprehension using timeit

The slowest run took 5.06 times longer than the fastest. This could mean that an intermediate result is being cached.
4.9 µs ± 3.76 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%time [i+2 for i in k] #list comprehension using time

CPU times: user 22 µs, sys: 2 µs, total: 24 µs
Wall time: 27.7 µs


[2, 3, 4, 5, 6, 7, 8]

In [ ]:
%timeit np.arange(size)+2 #element wise addition

3.16 µs ± 273 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit k*2 #element wise multiplication

1.47 µs ± 286 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
%timeit [i*2 for i in k] #list comprehension multiplication using timeit

2.11 µs ± 84.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit k**2 #element wise exponentiation

800 ns ± 273 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
%timeit [i**2 for i in k] #list comprehension exponentiation using timeit

2.17 µs ± 83.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%time k**2 #element wise exponentiation

CPU times: user 24 µs, sys: 0 ns, total: 24 µs
Wall time: 26.9 µs


array([ 0,  1,  4,  9, 16, 25, 36])

In [ ]:
%timeit np.sqrt(k) #element wise square root

1.16 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
%time np.sqrt(k)

CPU times: user 34 µs, sys: 1 µs, total: 35 µs
Wall time: 38.4 µs


array([0.  , 1.  , 1.41, 1.73, 2.  , 2.24, 2.45])

In [ ]:
%timeit np.exp(k) #element wise exponential

2.12 µs ± 295 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit [i**0.5 for i in k] #list comprehension exponential using timeit

15.8 µs ± 4.14 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit np.log(k) #element wise logarithm

<magic-timeit>:1: RuntimeWarning: divide by zero encountered in log


2.32 µs ± 118 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
np.random.seed(123)
(np.random.randint(1,11,1000000).reshape(10000,100).sum(axis=1)).mean() # Removed the comparison operator, assuming you wanted to reshape to a 10000x100 array

550.3482

In [ ]:
%timeit (np.random.randint(1,11,100*10000).reshape(10000,100).sum(axis=1)).mean()

17.8 ms ± 1.72 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
(np.random.randint(1,11,10000*100).reshape(10000,100)==1 ).sum(axis=1).mean()

10.0036

In [ ]:
np.random.seed(7)
F = np.random.randint(1,101,11, )
F

array([48, 69, 26, 68, 84, 24, 93, 58, 15, 24, 73])

In [ ]:
F.sort()
F

array([15, 24, 24, 26, 48, 58, 68, 69, 73, 84, 93])

In [ ]:
F.max()

93

In [ ]:
F.min()

15

In [ ]:
F.mean()

52.90909090909091

In [ ]:
np.mean(F)

52.90909090909091

In [ ]:
np.median(F)

58.0

In [ ]:
F.std()

25.84377732542751

In [ ]:
F.var()

667.900826446281

In [ ]:
np.percentile(F,25)

25.0

In [ ]:
np.percentile(F,75)

71.0

In [ ]:
np.percentile(F,50)

58.0

In [ ]:
np.percentile(F,[25,50,75])

array([25., 58., 71.])

In [ ]:
np.random.seed(3)
G = np.random.randint(1,101,11)
G

array([25,  4, 57, 73,  1, 22, 20, 75, 42, 11, 22])

In [ ]:
np.cov(F,G)

array([[734.69, -99.2 ],
       [-99.2 , 683.4 ]])

In [ ]:
np.correlate(F,G)

array([17632])

In [ ]:
np.corrcoef(F,G)

array([[ 1.  , -0.14],
       [-0.14,  1.  ]])

In [ ]:
np.linspace(0,10,121)

array([ 0.  ,  0.08,  0.17,  0.25,  0.33,  0.42,  0.5 ,  0.58,  0.67,
        0.75,  0.83,  0.92,  1.  ,  1.08,  1.17,  1.25,  1.33,  1.42,
        1.5 ,  1.58,  1.67,  1.75,  1.83,  1.92,  2.  ,  2.08,  2.17,
        2.25,  2.33,  2.42,  2.5 ,  2.58,  2.67,  2.75,  2.83,  2.92,
        3.  ,  3.08,  3.17,  3.25,  3.33,  3.42,  3.5 ,  3.58,  3.67,
        3.75,  3.83,  3.92,  4.  ,  4.08,  4.17,  4.25,  4.33,  4.42,
        4.5 ,  4.58,  4.67,  4.75,  4.83,  4.92,  5.  ,  5.08,  5.17,
        5.25,  5.33,  5.42,  5.5 ,  5.58,  5.67,  5.75,  5.83,  5.92,
        6.  ,  6.08,  6.17,  6.25,  6.33,  6.42,  6.5 ,  6.58,  6.67,
        6.75,  6.83,  6.92,  7.  ,  7.08,  7.17,  7.25,  7.33,  7.42,
        7.5 ,  7.58,  7.67,  7.75,  7.83,  7.92,  8.  ,  8.08,  8.17,
        8.25,  8.33,  8.42,  8.5 ,  8.58,  8.67,  8.75,  8.83,  8.92,
        9.  ,  9.08,  9.17,  9.25,  9.33,  9.42,  9.5 ,  9.58,  9.67,
        9.75,  9.83,  9.92, 10.  ])

In [ ]:
np.polyfit(F,G,1)

array([-0.14, 39.14])

In [ ]:
np.poly1d(np.polyfit(F,G,1))

poly1d([-0.14, 39.14])

In [ ]:
np.polyval(np.polyfit(F,G,1),F)

array([37.12, 35.9 , 35.9 , 35.63, 32.66, 31.31, 29.96, 29.83, 29.29,
       27.8 , 26.59])

In [ ]:
np.polyder(np.polyfit(F,G,1))

array([-0.14])

In [ ]:
np.arange(6, 19, 3)

array([ 6,  9, 12, 15, 18])